### PR TITLE
Use temp file and rename when saving config

### PR DESCRIPTION
**Pull request by jamesd**
Adds a new private save method for writing the new configuration to a
temp file then use rename to atomically overwrite the old
configuration.

### CODE REVIEW

**Comment by c-14** [comment]
Any reason not to completely drop GrueConfig.write() and use your save instead?

**Comment by jamesd** [comment]
Grepping, I notice I totally missed the use of write() in ImportCfg(). I'll change that.

The use of write() in writeDefConfig() I left as in that use case, there should not be an existing config to overwrite. However, as that is the last use of write, the semantics probably don't matter. I'll change that too.

**Comment by jamesd** [comment]
Replaced remaining 2 uses of write() with save().

**Comment by c-14** [comment]
Merged, thanks

**Pull request merged**
